// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIREudhWzSP3VBmZz-B0MACWaWWh1u7G8',
    appId: '1:715329198566:web:51fe03a01b6eacdde4de27',
    messagingSenderId: '715329198566',
    projectId: 'irismessapp',
    authDomain: 'irismessapp.firebaseapp.com',
    databaseURL: 'https://irismessapp-default-rtdb.firebaseio.com',
    storageBucket: 'irismessapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSpRo3mF52AwugeXWP19lUIt1ipYoJ5gQ',
    appId: '1:715329198566:android:3606c4a39356032ce4de27',
    messagingSenderId: '715329198566',
    projectId: 'irismessapp',
    databaseURL: 'https://irismessapp-default-rtdb.firebaseio.com',
    storageBucket: 'irismessapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9yHz18fukfhd_UGTrUPUTuRO_cJFwX1s',
    appId: '1:715329198566:ios:7fa26474f0fd5ed8e4de27',
    messagingSenderId: '715329198566',
    projectId: 'irismessapp',
    databaseURL: 'https://irismessapp-default-rtdb.firebaseio.com',
    storageBucket: 'irismessapp.appspot.com',
    iosBundleId: 'com.example.messmanager',
  );
}
